/*
 * SCHIMMILAB – Experimente Page
 * Design: Deep Space Lab – experiment log with status, hypothesis, learnings
 * Data source: client/src/data/experiments.ts (auto-generated by sync-anytype.py)
 * Features: Category filter, status badges, expandable experiment cards
 */

import { useState } from "react";
import { Link } from "wouter";
import { FlaskConical, ChevronRight, Tag, Calendar, CheckCircle2, Clock, AlertCircle, Archive, ArrowRight } from "lucide-react";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import { experiments } from "@/data/experiments";

const STATUS_ICONS: Record<string, React.ElementType> = {
  completed:   CheckCircle2,
  in_progress: Clock,
  planned:     AlertCircle,
  archived:    Archive,
};

export default function Experimente() {
  const [activeCategory, setActiveCategory] = useState("Alle");
  const [expandedId, setExpandedId] = useState<string | null>(null);

  // Derive categories dynamically from actual data
  const categories = ["Alle", ...Array.from(new Set(experiments.map((e) => e.category))).sort()];

  const filtered = activeCategory === "Alle"
    ? experiments
    : experiments.filter((e) => e.category === activeCategory);

  return (
    <div className="min-h-screen bg-background text-foreground">
      <Navigation />

      {/* Page Header */}
      <section
        className="pt-32 pb-16 border-b border-border relative overflow-hidden"
        style={{
          backgroundImage: `url(https://d2xsxph8kpxj0f.cloudfront.net/310519663389462490/3xYo7pHCgsopwwKpeL4Smu/experiments-bg-AWqnQoBzzykG4TYMzsRmPC.webp)`,
          backgroundSize: "cover",
          backgroundPosition: "center",
        }}
      >
        <div className="absolute inset-0 bg-background/85" />
        <div className="absolute inset-0 hex-pattern opacity-20" />
        <div className="relative z-10 container">
          <p className="text-xs text-[#00d4ff] uppercase tracking-widest mb-3" style={{ fontFamily: "var(--font-mono)" }}>
            // 01 — Experimente
          </p>
          <h1 className="text-4xl md:text-6xl font-bold mb-4" style={{ fontFamily: "var(--font-display)" }}>
            Das Labor
            <br />
            <span className="text-[#00d4ff]">ist offen.</span>
          </h1>
          <p className="text-muted-foreground max-w-xl leading-relaxed" style={{ fontFamily: "var(--font-body)" }}>
            Nicht nur "so geht's", sondern: Problem → Hypothese → Umsetzung → Ergebnis → Learnings.
            Systemisches Denken, sichtbar gemacht.
          </p>
          {experiments.length > 0 && (
            <p className="mt-4 text-xs text-muted-foreground" style={{ fontFamily: "var(--font-mono)" }}>
              // {experiments.length} Experimente aus Anytype synchronisiert
            </p>
          )}
        </div>
      </section>

      {/* Filter */}
      <section className="sticky top-16 md:top-20 z-30 bg-background/90 backdrop-blur-md border-b border-border">
        <div className="container py-4">
          <div className="flex items-center gap-2 overflow-x-auto pb-1 scrollbar-hide">
            {categories.map((cat) => (
              <button
                key={cat}
                onClick={() => setActiveCategory(cat)}
                className={`flex-shrink-0 px-4 py-1.5 text-xs transition-all duration-200 ${
                  activeCategory === cat
                    ? "bg-[#00d4ff] text-background font-semibold"
                    : "border border-border text-muted-foreground hover:text-foreground hover:border-[#00d4ff]/40"
                }`}
                style={{ fontFamily: "var(--font-mono)" }}
              >
                {cat}
              </button>
            ))}
            <span className="ml-auto text-xs text-muted-foreground flex-shrink-0" style={{ fontFamily: "var(--font-mono)" }}>
              {filtered.length} Experimente
            </span>
          </div>
        </div>
      </section>

      {/* Experiments List */}
      <section className="py-12">
        <div className="container">
          {experiments.length === 0 ? (
            <div className="text-center py-24">
              <FlaskConical className="w-12 h-12 text-[#00d4ff]/30 mx-auto mb-4" />
              <p className="text-xs text-muted-foreground uppercase tracking-widest mb-3" style={{ fontFamily: "var(--font-mono)" }}>
                // Noch keine Experimente synchronisiert
              </p>
              <p className="text-muted-foreground max-w-md mx-auto" style={{ fontFamily: "var(--font-body)" }}>
                Erstelle Objekte vom Typ "Experimente" in deinem Anytype Schimmilab Space.
              </p>
            </div>
          ) : (
            <div className="space-y-4">
              {filtered.map((exp, i) => {
                const isExpanded = expandedId === exp.id;
                const StatusIcon = STATUS_ICONS[exp.status] ?? FlaskConical;

                return (
                  <article
                    key={exp.id}
                    className={`border transition-all duration-300 overflow-hidden ${
                      isExpanded
                        ? "border-[#00d4ff]/50 shadow-[0_0_30px_rgba(0,212,255,0.08)]"
                        : "border-border hover:border-[#00d4ff]/30"
                    } bg-card`}
                    style={{ animationDelay: `${i * 50}ms` }}
                  >
                    {/* Card Header */}
                    <button
                      onClick={() => setExpandedId(isExpanded ? null : exp.id)}
                      className="w-full text-left p-6 flex items-start gap-4"
                    >
                      <div className="flex-1 min-w-0">
                        <div className="flex flex-wrap items-center gap-3 mb-2">
                          <span className="text-xs text-[#00d4ff]" style={{ fontFamily: "var(--font-mono)" }}>
                            {exp.category}
                          </span>
                          <span className="text-xs text-muted-foreground flex items-center gap-1" style={{ fontFamily: "var(--font-mono)" }}>
                            <Calendar className="w-3 h-3" />
                            {exp.date}
                          </span>
                          <span
                            className={`text-xs flex items-center gap-1 ${exp.statusColor}`}
                            style={{ fontFamily: "var(--font-mono)" }}
                          >
                            <StatusIcon className="w-3 h-3" />
                            {exp.statusLabel}
                          </span>
                        </div>
                        <h2 className="text-lg font-semibold text-foreground" style={{ fontFamily: "var(--font-display)" }}>
                          {exp.title}
                        </h2>
                        {!isExpanded && exp.excerpt && (
                          <p className="text-sm text-muted-foreground mt-1 line-clamp-2" style={{ fontFamily: "var(--font-body)" }}>
                            {exp.excerpt}
                          </p>
                        )}
                      </div>
                      <ChevronRight
                        className={`w-4 h-4 text-muted-foreground flex-shrink-0 mt-1 transition-transform duration-300 ${
                          isExpanded ? "rotate-90 text-[#00d4ff]" : ""
                        }`}
                      />
                    </button>

                    {/* Expanded Content */}
                    {isExpanded && (
                      <div className="px-6 pb-6 border-t border-border">
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-6">
                          {[
                            { label: "Problem",   content: exp.problem,   color: "text-red-400" },
                            { label: "Hypothese", content: exp.hypothese, color: "text-[#f59e0b]" },
                            { label: "Ergebnis",  content: exp.ergebnis,  color: "text-emerald-400" },
                            { label: "Learnings", content: exp.learnings, color: "text-[#00d4ff]" },
                          ].filter((s) => s.content?.trim()).map((section) => (
                            <div key={section.label}>
                              <p
                                className={`text-xs uppercase tracking-wider mb-2 ${section.color}`}
                                style={{ fontFamily: "var(--font-mono)" }}
                              >
                                // {section.label}
                              </p>
                              <p className="text-sm text-muted-foreground leading-relaxed line-clamp-4" style={{ fontFamily: "var(--font-body)" }}>
                                {section.content}
                              </p>
                            </div>
                          ))}
                        </div>

                        {/* Tags */}
                        <div className="flex flex-wrap gap-2 mt-6">
                          <Tag className="w-3 h-3 text-muted-foreground mt-0.5" />
                          {exp.tags.map((tag) => (
                            <span
                              key={tag}
                              className="text-xs px-2 py-0.5 bg-secondary text-muted-foreground"
                              style={{ fontFamily: "var(--font-mono)" }}
                            >
                              {tag}
                            </span>
                          ))}
                        </div>

                        {/* Link to full detail page */}
                        <div className="mt-6 pt-4 border-t border-border">
                          <Link
                            href={`/experimente/${exp.id}`}
                            className="inline-flex items-center gap-2 px-4 py-2 bg-[#00d4ff]/10 border border-[#00d4ff]/30 text-[#00d4ff] text-xs hover:bg-[#00d4ff]/20 transition-all duration-200"
                            style={{ fontFamily: "var(--font-mono)" }}
                          >
                            Vollständig lesen
                            <ArrowRight className="w-3 h-3" />
                          </Link>
                        </div>
                      </div>
                    )}
                  </article>
                );
              })}
            </div>
          )}
        </div>
      </section>

      <Footer />
    </div>
  );
}
