/*
 * SCHIMMILAB – Gedankenraum Page
 * Design: Deep Space Lab – philosophical articles with amber accent
 * Data source: client/src/data/thoughts.ts (auto-generated by sync-anytype.py)
 * Features: Article cards, featured article, Anytype-synced content
 */

import { Link } from "wouter";
import { Brain, ChevronRight, Calendar, Clock, Tag } from "lucide-react";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import { thoughts } from "@/data/thoughts";

// Static fallback articles shown when Anytype has no content yet
const FALLBACK_ARTICLES = [
  {
    id: "ki-als-werkzeug",
    date: "2026-02-25",
    readTime: 8,
    tags: ["KI", "Bewusstsein", "Philosophie"],
    title: "KI als Werkzeug oder als Gegenüber?",
    excerpt:
      "Die Frage ist nicht ob KI denkt, sondern was wir tun, wenn wir so tun als ob. Eine Analyse der anthropomorphen Projektion auf Sprachmodelle.",
    content: "",
    isFallback: true,
  },
  {
    id: "kontrolle-vs-autonomie",
    date: "2026-02-10",
    readTime: 6,
    tags: ["Kubernetes", "Systemdenken", "Selbstorganisation"],
    title: "Kontrolle vs. Autonomie in verteilten Systemen",
    excerpt:
      "Was Kubernetes und Selbstorganisation gemeinsam haben – und warum beides scheitert, wenn man es falsch versteht.",
    content: "",
    isFallback: true,
  },
  {
    id: "self-hosting-politisch",
    date: "2026-01-28",
    readTime: 5,
    tags: ["Self-Hosting", "Datenschutz", "Digitale Souveränität"],
    title: "Warum Self-Hosting politisch ist",
    excerpt:
      "Daten auf eigenem Server zu hosten ist keine technische Entscheidung. Es ist eine politische.",
    content: "",
    isFallback: true,
  },
];

export default function Gedankenraum() {
  // Merge Anytype thoughts with fallback articles
  // Anytype content takes priority; fallback fills up to 3 visible cards
  const anytypeItems = thoughts.map((t) => ({ ...t, isFallback: false }));
  const fallbackItems = FALLBACK_ARTICLES.filter(
    (f) => !anytypeItems.some((a) => a.id === f.id)
  );
  const allItems = [...anytypeItems, ...fallbackItems];

  const featured = allItems[0];
  const rest = allItems.slice(1, 4);

  return (
    <div className="min-h-screen bg-background text-foreground">
      <title>Gedankenraum – Schimmilab</title>
      <meta name="description" content="Artikel und Reflexionen wo Technik auf Bewusstsein trifft: KI, Systemdenken, Self-Hosting-Philosophie und mehr." />
      <Navigation />

      {/* ─── PAGE HEADER ─── */}
      <section
        className="pt-32 pb-16 border-b border-border relative overflow-hidden"
        style={{
          backgroundImage: `url(https://d2xsxph8kpxj0f.cloudfront.net/310519663389462490/3xYo7pHCgsopwwKpeL4Smu/thoughts-bg-LqCLYtcTf6MaX6zos3HLHG.webp)`,
          backgroundSize: "cover",
          backgroundPosition: "center top",
        }}
      >
        <div className="absolute inset-0 bg-background/85" />
        <div className="absolute inset-0 hex-pattern opacity-20" />
        <div className="relative z-10 container">
          <p
            className="text-xs text-[#f59e0b] uppercase tracking-widest mb-3"
            style={{ fontFamily: "var(--font-mono)" }}
          >
            // 03 — Gedankenraum
          </p>
          <h1
            className="text-4xl md:text-6xl font-bold mb-4"
            style={{ fontFamily: "var(--font-display)" }}
          >
            Kein Geschwurbel.
            <br />
            <span className="text-[#f59e0b]">Saubere Argumentation.</span>
          </h1>
          <p
            className="text-muted-foreground max-w-xl leading-relaxed"
            style={{ fontFamily: "var(--font-body)" }}
          >
            Technik & Machtstrukturen. KI & Bewusstsein. Kontrolle vs.
            Autonomie. Brutal logisch, auch wenn die Informationen
            widersprüchlich sind.
          </p>
          {thoughts.length > 0 && (
            <p
              className="mt-4 text-xs text-muted-foreground"
              style={{ fontFamily: "var(--font-mono)" }}
            >
              // {thoughts.length} Gedanken aus Anytype synchronisiert
            </p>
          )}
        </div>
      </section>

      {/* ─── FEATURED ARTICLE ─── */}
      {featured && (
        <section className="py-16 border-b border-border">
          <div className="container">
            <p
              className="text-xs text-[#f59e0b] uppercase tracking-widest mb-6"
              style={{ fontFamily: "var(--font-mono)" }}
            >
              // Aktueller Gedanke
            </p>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 items-start">
              {/* Left: meta + title + excerpt */}
              <div>
                <div className="flex items-center gap-3 mb-4">
                  <span
                    className="text-xs text-muted-foreground flex items-center gap-1"
                    style={{ fontFamily: "var(--font-mono)" }}
                  >
                    <Calendar className="w-3 h-3" />
                    {featured.date}
                  </span>
                  <span
                    className="text-xs text-muted-foreground flex items-center gap-1"
                    style={{ fontFamily: "var(--font-mono)" }}
                  >
                    <Clock className="w-3 h-3" />
                    {featured.readTime} min
                  </span>
                </div>
                <h2
                  className="text-3xl md:text-4xl font-bold mb-4 leading-tight"
                  style={{ fontFamily: "var(--font-display)" }}
                >
                  {featured.title}
                </h2>
                <p
                  className="text-muted-foreground leading-relaxed mb-6"
                  style={{ fontFamily: "var(--font-body)" }}
                >
                  {featured.excerpt}
                </p>
                <div className="flex flex-wrap gap-2 mb-6">
                  {featured.tags.map((tag) => (
                    <span
                      key={tag}
                      className="text-xs px-2 py-0.5 bg-[#f59e0b]/10 text-[#f59e0b] border border-[#f59e0b]/30"
                      style={{ fontFamily: "var(--font-mono)" }}
                    >
                      {tag}
                    </span>
                  ))}
                </div>

                {/* Link to detail page if not a fallback */}
                {!featured.isFallback ? (
                  <Link
                    href={`/gedankenraum/${featured.id}`}
                    className="inline-flex items-center gap-2 px-5 py-2.5 bg-[#f59e0b] text-background text-sm font-semibold hover:bg-[#f59e0b]/90 transition-all duration-200"
                    style={{ fontFamily: "var(--font-display)" }}
                  >
                    <Brain className="w-4 h-4" />
                    Weiterlesen
                  </Link>
                ) : (
                  <div
                    className="inline-flex items-center gap-2 px-5 py-2.5 bg-[#f59e0b]/10 text-[#f59e0b]/60 border border-[#f59e0b]/20 text-sm font-semibold select-none"
                    style={{ fontFamily: "var(--font-display)" }}
                  >
                    <Brain className="w-4 h-4" />
                    Demnächst in Anytype
                  </div>
                )}
              </div>

              {/* Right: content preview */}
              <div className="border border-[#f59e0b]/30 bg-card p-6">
                <p
                  className="text-xs text-[#f59e0b] mb-4 uppercase tracking-widest"
                  style={{ fontFamily: "var(--font-mono)" }}
                >
                  // Auszug
                </p>
                {featured.content ? (
                  <div
                    className="text-sm text-muted-foreground leading-relaxed space-y-4"
                    style={{ fontFamily: "var(--font-body)" }}
                  >
                    {featured.content
                      .split("\n\n")
                      .slice(0, 3)
                      .map((para, i) => (
                        <p key={i}>{para}</p>
                      ))}
                    <p
                      className="text-[#f59e0b] text-xs"
                      style={{ fontFamily: "var(--font-mono)" }}
                    >
                      [...] Vollständiger Artikel →
                    </p>
                  </div>
                ) : (
                  <p
                    className="text-sm text-muted-foreground italic"
                    style={{ fontFamily: "var(--font-body)" }}
                  >
                    {featured.excerpt}
                  </p>
                )}
              </div>
            </div>
          </div>
        </section>
      )}

      {/* ─── ARTICLE GRID ─── */}
      {rest.length > 0 && (
        <section className="py-16">
          <div className="container">
            <p
              className="text-xs text-[#f59e0b] uppercase tracking-widest mb-8"
              style={{ fontFamily: "var(--font-mono)" }}
            >
              // Weitere Gedanken
            </p>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {rest.map((article, i) =>
                !article.isFallback ? (
                  <Link
                    key={article.id}
                    href={`/gedankenraum/${article.id}`}
                    className="group border border-border bg-card hover:border-[#f59e0b]/40 transition-all duration-300 p-6 flex flex-col gap-4"
                    style={{ animationDelay: `${i * 80}ms` }}
                  >
                    <ArticleCardContent article={article} />
                  </Link>
                ) : (
                  <article
                    key={article.id}
                    className="group border border-border bg-card p-6 flex flex-col gap-4 opacity-60"
                    style={{ animationDelay: `${i * 80}ms` }}
                  >
                    <ArticleCardContent article={article} isFallback />
                  </article>
                )
              )}
            </div>
          </div>
        </section>
      )}

      {/* ─── EMPTY STATE (if no content yet) ─── */}
      {allItems.length === 0 && (
        <section className="py-32">
          <div className="container text-center">
            <Brain className="w-12 h-12 text-[#f59e0b]/40 mx-auto mb-6" />
            <p
              className="text-xs text-muted-foreground uppercase tracking-widest mb-4"
              style={{ fontFamily: "var(--font-mono)" }}
            >
              // Noch keine Gedanken synchronisiert
            </p>
            <p
              className="text-muted-foreground max-w-md mx-auto"
              style={{ fontFamily: "var(--font-body)" }}
            >
              Erstelle Gedanken vom Typ "Gedankenraum" in deinem Anytype
              Schimmilab Space. Sie werden beim nächsten Sync automatisch hier
              erscheinen.
            </p>
          </div>
        </section>
      )}

      {/* ─── INDITRITIUM QUOTE ─── */}
      <section className="py-16 border-t border-border bg-card/20">
        <div className="container">
          <div className="max-w-2xl">
            <p
              className="text-xs text-muted-foreground uppercase tracking-widest mb-4"
              style={{ fontFamily: "var(--font-mono)" }}
            >
              // Verbindung zu Arcanara
            </p>
            <blockquote
              className="text-lg font-medium text-foreground leading-relaxed border-l-2 border-[#f59e0b] pl-6"
              style={{ fontFamily: "var(--font-display)" }}
            >
              "Schimmilab ist die technische Schwester von Arcanara. Wo Arcanara
              die Fragen stellt, versucht Schimmilab, sie mit Code und
              Lötkolben zu beantworten."
            </blockquote>
            <p
              className="mt-4 text-sm text-muted-foreground"
              style={{ fontFamily: "var(--font-mono)" }}
            >
              — Das Inditritium: Der Raum zwischen dem Bekannten und dem
              Unbekannten
            </p>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}

// ─── Sub-component: Article card content ──────────────────────────────────────
function ArticleCardContent({
  article,
  isFallback = false,
}: {
  article: { title: string; date: string; readTime: number; tags: string[]; excerpt: string };
  isFallback?: boolean;
}) {
  return (
    <>
      <div
        className="flex items-center gap-3 text-xs text-muted-foreground"
        style={{ fontFamily: "var(--font-mono)" }}
      >
        <span className="flex items-center gap-1">
          <Calendar className="w-3 h-3" />
          {article.date}
        </span>
        <span className="flex items-center gap-1">
          <Clock className="w-3 h-3" />
          {article.readTime} min
        </span>
      </div>
      <h3
        className="text-lg font-semibold text-foreground group-hover:text-[#f59e0b] transition-colors leading-snug"
        style={{ fontFamily: "var(--font-display)" }}
      >
        {article.title}
      </h3>
      <p
        className="text-sm text-muted-foreground leading-relaxed flex-1"
        style={{ fontFamily: "var(--font-body)" }}
      >
        {article.excerpt}
      </p>
      <div className="flex flex-wrap gap-1.5">
        {article.tags.slice(0, 3).map((tag) => (
          <span
            key={tag}
            className="flex items-center gap-1 text-xs px-1.5 py-0.5 bg-secondary text-muted-foreground"
            style={{ fontFamily: "var(--font-mono)" }}
          >
            <Tag className="w-2.5 h-2.5" />
            {tag}
          </span>
        ))}
      </div>
      {!isFallback && (
        <div
          className="flex items-center gap-1 text-xs text-[#f59e0b] opacity-0 group-hover:opacity-100 transition-opacity"
          style={{ fontFamily: "var(--font-mono)" }}
        >
          <span>Weiterlesen</span>
          <ChevronRight className="w-3 h-3" />
        </div>
      )}
    </>
  );
}
