/*
 * SCHIMMILAB – Gedanken Detail Page
 * Design: Deep Space Lab – long-form article with amber accent
 * Data source: client/src/data/thoughts.ts (auto-generated by sync-anytype.py)
 */

import { useParams, Link, useLocation } from "wouter";
import { useEffect, useMemo } from "react";
import { ArrowLeft, Clock, Tag, Brain, ChevronRight, Calendar } from "lucide-react";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import MarkdownContent from "@/components/MarkdownContent";
import { getThoughtById, thoughts } from "@/data/thoughts";

export default function GedankenDetail() {
  const { id } = useParams<{ id: string }>();
  const [location] = useLocation();
  const thought = useMemo(() => getThoughtById(id), [id]);

  // Scroll to top on navigation
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  }, [id, location]);

  // ── 404 ──────────────────────────────────────────────────────────────────────
  if (!thought) {
    return (
      <div className="min-h-screen bg-background text-foreground">
        <Navigation />
        <main id="main-content">
        <div className="container pt-40 pb-20 text-center">
          <p
            className="text-muted-foreground text-sm mb-4"
            style={{ fontFamily: "var(--font-mono)" }}
          >
            // 404 — Gedanke nicht gefunden
          </p>
          <h1
            className="text-4xl font-bold mb-8"
            style={{ fontFamily: "var(--font-display)" }}
          >
            Dieser Gedanke existiert nicht.
          </h1>
          <Link
            href="/gedankenraum"
            className="inline-flex items-center gap-2 text-[#f59e0b] hover:underline"
          >
            <ArrowLeft className="w-4 h-4" />
            Zurück zum Gedankenraum
          </Link>
        </div>
        </main>
        <Footer />
      </div>
    );
  }

  // Other thoughts for "Weitere Gedanken" section
  const others = thoughts.filter((t) => t.id !== thought.id).slice(0, 2);

  return (
    <div className="min-h-screen bg-background text-foreground">
      <title>{thought.title} – Schimmilab</title>
      <meta name="description" content={thought.excerpt} />
      <Navigation />
      <main id="main-content">

      {/* ─── HEADER ─── */}
      <section className="pt-32 pb-12 border-b border-border">
        <div className="container">
          {/* Breadcrumb */}
          <nav
            className="flex items-center gap-2 text-xs text-muted-foreground mb-8"
            style={{ fontFamily: "var(--font-mono)" }}
          >
            <Link href="/" className="hover:text-[#f59e0b] transition-colors">
              Start
            </Link>
            <ChevronRight className="w-3 h-3" />
            <Link
              href="/gedankenraum"
              className="hover:text-[#f59e0b] transition-colors"
            >
              Gedankenraum
            </Link>
            <ChevronRight className="w-3 h-3" />
            <span className="text-foreground">{thought.id}</span>
          </nav>

          {/* Meta row */}
          <div className="flex flex-wrap items-center gap-4 mb-6">
            <span
              className="text-xs text-muted-foreground flex items-center gap-1"
              style={{ fontFamily: "var(--font-mono)" }}
            >
              <Calendar className="w-3 h-3" />
              {thought.date}
            </span>
            <span
              className="flex items-center gap-1 text-xs text-muted-foreground"
              style={{ fontFamily: "var(--font-mono)" }}
            >
              <Clock className="w-3 h-3" />
              {thought.readTime} min Lesezeit
            </span>
          </div>

          {/* Title */}
          <h1
            className="text-4xl md:text-5xl lg:text-6xl font-bold leading-tight mb-6 max-w-4xl"
            style={{ fontFamily: "var(--font-display)" }}
          >
            {thought.title}
          </h1>

          {/* Excerpt */}
          <p
            className="text-lg text-muted-foreground max-w-2xl leading-relaxed mb-8"
            style={{ fontFamily: "var(--font-body)" }}
          >
            {thought.excerpt}
          </p>

          {/* Tags */}
          <div className="flex flex-wrap gap-2">
            {thought.tags.map((tag) => (
              <span
                key={tag}
                className="flex items-center gap-1 text-xs px-3 py-1 bg-[#f59e0b]/10 text-[#f59e0b] border border-[#f59e0b]/30"
                style={{ fontFamily: "var(--font-mono)" }}
              >
                <Tag className="w-3 h-3" />
                {tag}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* ─── CONTENT ─── */}
      <section className="py-16 md:py-24">
        <div className="container">
          <div className="grid grid-cols-1 lg:grid-cols-[1fr_260px] gap-12 max-w-5xl">

            {/* Main article body */}
            <article>
              {thought.content ? (
                <MarkdownContent content={thought.content} accentColor="#f59e0b" />
              ) : (
                // Empty state: thought exists but has no content yet
                <div className="border border-[#f59e0b]/20 bg-card p-8 text-center">
                  <Brain className="w-10 h-10 text-[#f59e0b]/40 mx-auto mb-4" />
                  <p
                    className="text-xs text-muted-foreground uppercase tracking-widest mb-3"
                    style={{ fontFamily: "var(--font-mono)" }}
                  >
                    // Inhalt noch nicht verfasst
                  </p>
                  <p
                    className="text-muted-foreground text-sm max-w-sm mx-auto"
                    style={{ fontFamily: "var(--font-body)" }}
                  >
                    Dieser Gedanke wurde in Anytype angelegt, aber noch nicht
                    ausformuliert. Füge Inhalt in Anytype hinzu – beim nächsten
                    Sync erscheint er hier.
                  </p>
                </div>
              )}
            </article>

            {/* Sidebar */}
            <aside className="space-y-6">
              <div className="border border-border bg-card p-5 sticky top-24">
                <p
                  className="text-xs text-[#f59e0b] uppercase tracking-widest mb-4"
                  style={{ fontFamily: "var(--font-mono)" }}
                >
                  // Info
                </p>
                <div className="space-y-3 text-sm text-muted-foreground">
                  <div className="flex items-center gap-2" style={{ fontFamily: "var(--font-mono)" }}>
                    <Calendar className="w-3.5 h-3.5 text-[#f59e0b]" />
                    <span>{thought.date}</span>
                  </div>
                  <div className="flex items-center gap-2" style={{ fontFamily: "var(--font-mono)" }}>
                    <Clock className="w-3.5 h-3.5 text-[#f59e0b]" />
                    <span>{thought.readTime} min Lesezeit</span>
                  </div>
                </div>

                {thought.tags.length > 0 && (
                  <div className="mt-5 pt-5 border-t border-border">
                    <p
                      className="text-xs text-[#f59e0b] uppercase tracking-widest mb-3"
                      style={{ fontFamily: "var(--font-mono)" }}
                    >
                      // Tags
                    </p>
                    <div className="flex flex-wrap gap-1.5">
                      {thought.tags.map((tag) => (
                        <span
                          key={tag}
                          className="text-xs px-2 py-0.5 bg-secondary text-muted-foreground"
                          style={{ fontFamily: "var(--font-mono)" }}
                        >
                          {tag}
                        </span>
                      ))}
                    </div>
                  </div>
                )}

                <div className="mt-6 pt-6 border-t border-border">
                  <Link
                    href="/gedankenraum"
                    className="flex items-center gap-2 text-sm text-muted-foreground hover:text-[#f59e0b] transition-colors"
                    style={{ fontFamily: "var(--font-body)" }}
                  >
                    <ArrowLeft className="w-4 h-4" />
                    Alle Gedanken
                  </Link>
                </div>
              </div>
            </aside>
          </div>
        </div>
      </section>

      {/* ─── WEITERE GEDANKEN ─── */}
      {others.length > 0 && (
        <section className="py-16 border-t border-border">
          <div className="container">
            <p
              className="text-xs text-[#f59e0b] uppercase tracking-widest mb-3"
              style={{ fontFamily: "var(--font-mono)" }}
            >
              // Weitere Gedanken
            </p>
            <h2
              className="text-2xl font-bold mb-8"
              style={{ fontFamily: "var(--font-display)" }}
            >
              Was sonst noch im Gedankenraum passiert
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 max-w-3xl">
              {others.map((t) => (
                <Link
                  key={t.id}
                  href={`/gedankenraum/${t.id}`}
                  className="group border border-border bg-card hover:border-[#f59e0b]/50 transition-all duration-300 hover:shadow-[0_0_20px_rgba(245,158,11,0.1)] p-5 flex flex-col gap-3"
                >
                  <div
                    className="flex items-center gap-2 text-xs text-muted-foreground"
                    style={{ fontFamily: "var(--font-mono)" }}
                  >
                    <Calendar className="w-3 h-3" />
                    {t.date}
                  </div>
                  <h3
                    className="font-semibold text-foreground group-hover:text-[#f59e0b] transition-colors leading-snug"
                    style={{ fontFamily: "var(--font-display)" }}
                  >
                    {t.title}
                  </h3>
                  <p
                    className="text-xs text-muted-foreground"
                    style={{ fontFamily: "var(--font-body)" }}
                  >
                    {t.excerpt}
                  </p>
                  <div
                    className="flex items-center gap-1 text-xs text-[#f59e0b] mt-auto"
                    style={{ fontFamily: "var(--font-mono)" }}
                  >
                    <Brain className="w-3 h-3" />
                    Lesen
                    <ChevronRight className="w-3 h-3" />
                  </div>
                </Link>
              ))}
            </div>
          </div>
        </section>
      )}

      </main>
      <Footer />
    </div>
  );
}
