// AUTO-GENERATED by scripts/sync-anytype.py
// Last sync: 2026-03-22T06:56:52.953250
// DO NOT EDIT MANUALLY – edit in Anytype Schimmilab Space instead

export interface InfraItem {
  id: string;
  anytype_id?: string;
  title: string;
  category: string;
  tags: string[];
  date: string;
  status: string;
  statusColor: string;
  statusLabel: string;
  excerpt: string;
  overview: string;
  stack: string;
  architecture: string;
  setup: string;
  costs: string;
  security: string;
  code: string;
  learnings: string;
}

export const infraItems: InfraItem[] = [
  {
    id: "schimmilabde-website-content-pipeline",
    anytype_id: "bafyreicx7abjr5nqdd2cdfhieerkrzk2gqvccxxp2rysz33pgz2zrmewyu",
    title: `schimmilab.de — Website & Content-Pipeline`,
    category: `Networking`,
    tags: ["Docker", "GitHub Actions", "Hetzner", "Traefik", "React", "Anytype"],
    date: "2026-03-21",
    status: "active",
    statusColor: "text-emerald-400",
    statusLabel: "Aktiv",
    excerpt: `Überblick Die öffentliche Website schimmilab.de — "Experimente zwischen Code, KI und Erkenntnis". Eine statisch gebaute React-SPA mit Express-Backend, die...`,
    overview: ``,
    stack: `- **Frontend:** React 19 + Vite 7 + TypeScript, Tailwind CSS v4, shadcn/ui (New York Style), wouter (Routing), Framer Motion   
- **Backend:** Express.js (Node) — dient nur statische Dateien aus, kein API-Layer   
- **Build:** Vite für Frontend-Bundle, esbuild für Server-Bundle   
- **Container:** Docker multi-stage build (Node build → nginx:alpine serving)   
- **Reverse Proxy:** Traefik mit automatischem Let's Encrypt TLS   
- **Registry:** GHCR (GitHub Container Registry)   
- **Content-Sync:** Python 3 (\`scripts/sync-anytype.py\`) + Anytype REST API`,
    architecture: `Anytype (CMS) → REST API (alle 6h via GitHub Actions) → sync-anytype.py → generiert TypeScript-Datendateien → Vite Build (statisch kompiliert) → Docker Image (nginx:alpine) → GHCR → Hetzner VPS → Traefik → schimmilab.de (TLS)   
Inhalte werden build-time statisch ins Bundle kompiliert — kein Runtime-API-Call zur Website. Dies macht die Site blitzschnell und ohne Backend-Abhängigkeit zur Laufzeit.`,
    setup: `Lokal entwickeln: \`pnpm install\` → \`pnpm dev\` (Port 3000)   
Bauen: \`pnpm build\` (Frontend + Server), \`pnpm start\` (Produktions-Server)   
Docker: \`docker build -t schimmilab .\` → \`docker run -p 3000:3000 schimmilab\`   
Content-Sync manuell: \`python3 scripts/sync-anytype.py\`   
Umgebungsvariablen für den Sync: \`ANYTYPE\\_API\\_KEY\` (API-Key) und \`ANYTYPE\\_SPACE\\_ID\` (Space-ID des Schimmilab-Spaces)`,
    costs: `- Hetzner VPS: Shared auf dem Hauptserver (kein dedizierter Aufwand)   
- GHCR: Kostenlos für öffentliche Images   
- GitHub Actions: Im Free-Tier (Sync alle 6h = ca. 120 Minuten/Monat)   
- Domain: schimmilab.de über externen Registrar`,
    security: `- TLS automatisch via Traefik + Let's Encrypt (ACME)   
- Keine sensitiven Daten im Container — Anytype API Key nur in GitHub Actions Secrets   
- nginx serving nur statische Dateien — keine serverseitige Angriffsfläche zur Laufzeit   
- Container läuft als non-root (nginx default)`,
    code: `**Repo:** https://github.com/Schimmilab/schimmilab\\_webpage`,
    learnings: `Der statische Build-Ansatz (Anytype → TS-Datendateien → Vite-Bundle) ist simpler als ein Runtime-API-Call, hat aber einen Nachteil: Inhaltsänderungen erscheinen erst nach dem nächsten Sync (max. 6h Verzögerung oder manueller Trigger). Für ein persönliches Lab-Projekt ist das absolut akzeptabel.   
Die Heading-Struktur in Anytype-Objekten muss mit dem Parser in \`sync-anytype.py\` übereinstimmen — Abweichungen führen zu leeren Sektionen auf der Website.`,
  },
  {
    id: "restic-backup-system",
    anytype_id: "bafyreiaah2fjsshh3575esjddbdnoe6a32ye7taujbjnnyt3vhgmsnh5ri",
    title: `Restic Backup System`,
    category: `Storage`,
    tags: ["Storage"],
    date: "2026-03-21",
    status: "active",
    statusColor: "text-emerald-400",
    statusLabel: "Aktiv",
    excerpt: `Automatische inkrementelle Backups aller wichtigen Daten zu Hetzner Storage Box via Restic.`,
    overview: `Automatische inkrementelle Backups aller wichtigen Daten zu Hetzner Storage Box via Restic.`,
    stack: `- **Restic**: v0.16.x   
- **Backend**: Hetzner Storage Box (SFTP)   
- **Schedule**: Täglich via systemd Timer   
- **Retention**: 7 daily, 4 weekly, 12 monthly`,
    architecture: ``,
    setup: `\`\`\`
# Restic installieren
apt install restic

# Repository initialisieren
restic -r sftp:user@your-storagebox.de:/backups init

# Backup Script /usr/local/bin/backup.sh
#!/bin/bash
export RESTIC_PASSWORD="your-password"
export RESTIC_REPOSITORY="sftp:user@your-storagebox.de:/backups"

restic backup   /var/lib/docker/volumes   /etc/traefik   /home/ubuntu/docker-compose.yml   --tag daily

restic forget   --keep-daily 7   --keep-weekly 4   --keep-monthly 12   --prune

\`\`\``,
    costs: `- Hetzner Storage Box 100GB: ~3€/Monat   
- Restic: Kostenlos`,
    security: ``,
    code: ``,
    learnings: `- Restic Snapshots vor größeren Änderungen machen   
- \`restic check\` regelmäßig ausführen   
- Backup-Passwort sicher aufbewahren (ohne es gibt es keine Wiederherstellung)`,
  },
  {
    id: "wireguard-vpn",
    anytype_id: "bafyreia2q7dlmizuhojav4llsmgnbm52smlmkhsok4snhv6u4kuwlfeswe",
    title: `WireGuard VPN`,
    category: `Networking`,
    tags: ["Networking"],
    date: "2026-03-21",
    status: "active",
    statusColor: "text-emerald-400",
    statusLabel: "Aktiv",
    excerpt: `WireGuard als VPN für sicheren Admin-Zugriff auf den Hetzner-Server. Alle Admin-Interfaces Portainer, Traefik Dashboard, Grafana sind nur über VPN erreichbar.`,
    overview: `WireGuard als VPN für sicheren Admin-Zugriff auf den Hetzner-Server. Alle Admin-Interfaces (Portainer, Traefik Dashboard, Grafana) sind nur über VPN erreichbar.`,
    stack: `- **WireGuard**: Kernel-Modul (Ubuntu 24.04 built-in)   
- **Port**: 51820/UDP   
- **Clients**: MacBook, iPhone, iPad`,
    architecture: ``,
    setup: `\`\`\`
# WireGuard installieren (Ubuntu 24.04 hat es bereits)
apt install wireguard

# Server Key generieren
wg genkey | tee /etc/wireguard/server_private.key | wg pubkey > /etc/wireguard/server_public.key

# Config /etc/wireguard/wg0.conf
[Interface]
PrivateKey = <server_private_key>
Address = 10.0.0.1/24
ListenPort = 51820
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey = <client_public_key>
AllowedIPs = 10.0.0.2/32

\`\`\``,
    costs: `- Kostenlos (Open Source, Kernel-Modul)`,
    security: ``,
    code: `- Split-Tunnel konfigurieren damit nur Server-Traffic durch VPN geht`,
    learnings: `- WireGuard ist deutlich einfacher als OpenVPN`,
  },
  {
    id: "traefik-reverse-proxy",
    anytype_id: "bafyreigmzipfavxbhbb7xnnnrd2juozia6xuqoehmw6uqwigwm6owy733y",
    title: `Traefik Reverse Proxy`,
    category: `Storage`,
    tags: ["Storage"],
    date: "2026-03-21",
    status: "active",
    statusColor: "text-emerald-400",
    statusLabel: "Aktiv",
    excerpt: `Traefik v3 als zentraler Reverse Proxy für alle Services. Automatische TLS-Zertifikate via Let's Encrypt, Service Discovery via Docker Labels.`,
    overview: `Traefik v3 als zentraler Reverse Proxy für alle Services. Automatische TLS-Zertifikate via Let's Encrypt, Service Discovery via Docker Labels.`,
    stack: `- **Traefik**: v3.x   
- **TLS**: Let's Encrypt (ACME) via TLS-Challenge   
- **DNS**: Cloudflare (für DNS-Challenge als Fallback)   
- **Dashboard**: Traefik Dashboard (intern via Authelia geschützt)`,
    architecture: `\`\`\`
Internet → Cloudflare CDN → Traefik → Services
                              ↓
                         Auto-TLS (ACME)
                         Rate Limiting
                         Auth Middleware (Authelia)

\`\`\``,
    setup: ``,
    costs: ``,
    security: `- Docker Socket Read-Only gemountet   
- Dashboard nur intern erreichbar   
- HTTP → HTTPS Redirect für alle Services   
- Rate Limiting via Middleware`,
    code: `\`\`\`
version: "3.8"

services:
  traefik:
    image: traefik:v3
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.email=\${ACME_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/certs/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs
    restart: unless-stopped

\`\`\``,
    learnings: `- Labels sind eleganter als nginx.conf   
- \`exposedbydefault=false\` ist wichtig für Security   
- Wildcard-Zertifikate brauchen DNS-Challenge (Cloudflare API Key nötig)`,
  },
  {
    id: "hetzner-server-setup",
    anytype_id: "bafyreietg27mnugy4e3p62f2lfjeiu6ci46karmvlzx4nc227yxfjgntty",
    title: `Hetzner Server Setup`,
    category: `Storage`,
    tags: ["Storage"],
    date: "2026-03-21",
    status: "active",
    statusColor: "text-emerald-400",
    statusLabel: "Aktiv",
    excerpt: `Hetzner CX21 als Basis für alle Schimmilab-Services. Günstig, zuverlässig, in Deutschland gehostet.`,
    overview: `Hetzner CX21 als Basis für alle Schimmilab-Services. Günstig, zuverlässig, in Deutschland gehostet.`,
    stack: `- **Server**: Hetzner CX21 (2 vCPU, 4GB RAM, 40GB SSD NVMe)   
- **OS**: Ubuntu 24.04 LTS   
- **Backup**: Hetzner Storage Box 100GB (~3€/Monat)   
- **Firewall**: UFW (nur Port 80, 443, 51820 offen)`,
    architecture: ``,
    setup: `\`\`\``,
    costs: `- Hetzner CX21: ~5€/Monat   
- Hetzner Storage Box: ~3€/Monat   
- **Gesamt: ~8€/Monat**`,
    security: ``,
    code: ``,
    learnings: `- CX21 reicht für 10+ Docker Services problemlos   
- Hetzner Snapshots als schnelles Backup vor größeren Änderungen   
- IPv6 aktivieren nicht vergessen`,
  },
];

export const getInfraItemById = (id: string): InfraItem | undefined =>
  infraItems.find((i) => i.id === id);

export const getInfraItemsByCategory = (category: string): InfraItem[] =>
  infraItems.filter((i) => i.category === category);
