// AUTO-GENERATED by scripts/sync-anytype.py
// Last sync: 2026-03-21T11:36:23.418894
// DO NOT EDIT MANUALLY – edit in Anytype Schimmilab Space instead

export interface InfraItem {
  id: string;
  anytype_id?: string;
  title: string;
  category: string;
  tags: string[];
  date: string;
  status: string;
  statusColor: string;
  statusLabel: string;
  excerpt: string;
  overview: string;
  stack: string;
  architecture: string;
  setup: string;
  costs: string;
  security: string;
  code: string;
  learnings: string;
}

export const infraItems: InfraItem[] = [
  {
    id: "restic-backup-system",
    anytype_id: "bafyreiaah2fjsshh3575esjddbdnoe6a32ye7taujbjnnyt3vhgmsnh5ri",
    title: `Restic Backup System`,
    category: `Storage`,
    tags: ["Storage"],
    date: "2026-03-21",
    status: "active",
    statusColor: "text-emerald-400",
    statusLabel: "Aktiv",
    excerpt: `Überblick Automatische inkrementelle Backups aller wichtigen Daten zu Hetzner Storage Box via Restic. Stack Restic: v0.16.x Backend: Hetzner Storage Box SFTP...`,
    overview: `Überblick
Automatische inkrementelle Backups aller wichtigen Daten zu Hetzner Storage Box via Restic.
Stack
Restic: v0.16.x
Backend: Hetzner Storage Box (SFTP)
Schedule: Täglich via systemd Timer
Retention: 7 daily, 4 weekly, 12 monthly
Setup
# Restic installieren
apt install restic

# Repository …`,
    stack: ``,
    architecture: ``,
    setup: ``,
    costs: ``,
    security: ``,
    code: ``,
    learnings: ``,
  },
  {
    id: "wireguard-vpn",
    anytype_id: "bafyreia2q7dlmizuhojav4llsmgnbm52smlmkhsok4snhv6u4kuwlfeswe",
    title: `WireGuard VPN`,
    category: `Container`,
    tags: ["Container"],
    date: "2026-03-21",
    status: "active",
    statusColor: "text-emerald-400",
    statusLabel: "Aktiv",
    excerpt: `Überblick WireGuard als VPN für sicheren Admin-Zugriff auf den Hetzner-Server. Alle Admin-Interfaces Portainer, Traefik Dashboard, Grafana sind nur über VPN...`,
    overview: `Überblick
WireGuard als VPN für sicheren Admin-Zugriff auf den Hetzner-Server. Alle Admin-Interfaces (Portainer, Traefik Dashboard, Grafana) sind nur über VPN erreichbar.
Stack
WireGuard: Kernel-Modul (Ubuntu 24.04 built-in)
Port: 51820/UDP
Clients: MacBook, iPhone, iPad
Setup
# WireGuard …`,
    stack: ``,
    architecture: ``,
    setup: ``,
    costs: ``,
    security: ``,
    code: ``,
    learnings: ``,
  },
  {
    id: "traefik-reverse-proxy",
    anytype_id: "bafyreigmzipfavxbhbb7xnnnrd2juozia6xuqoehmw6uqwigwm6owy733y",
    title: `Traefik Reverse Proxy`,
    category: `Container`,
    tags: ["Container"],
    date: "2026-03-21",
    status: "active",
    statusColor: "text-emerald-400",
    statusLabel: "Aktiv",
    excerpt: `Überblick Traefik v3 als zentraler Reverse Proxy für alle Services. Automatische TLS-Zertifikate via Let's Encrypt, Service Discovery via Docker Labels. Stack...`,
    overview: `Überblick
Traefik v3 als zentraler Reverse Proxy für alle Services. Automatische TLS-Zertifikate via Let's Encrypt, Service Discovery via Docker Labels.
Stack
Traefik: v3.x
TLS: Let's Encrypt (ACME) via TLS-Challenge
DNS: Cloudflare (für DNS-Challenge als Fallback)
Dashboard: Traefik Dashboard …`,
    stack: ``,
    architecture: ``,
    setup: ``,
    costs: ``,
    security: ``,
    code: ``,
    learnings: ``,
  },
  {
    id: "hetzner-server-setup",
    anytype_id: "bafyreietg27mnugy4e3p62f2lfjeiu6ci46karmvlzx4nc227yxfjgntty",
    title: `Hetzner Server Setup`,
    category: `Storage`,
    tags: ["Storage"],
    date: "2026-03-21",
    status: "active",
    statusColor: "text-emerald-400",
    statusLabel: "Aktiv",
    excerpt: `Überblick Hetzner CX21 als Basis für alle Schimmilab-Services. Günstig, zuverlässig, in Deutschland gehostet. Stack Server: Hetzner CX21 2 vCPU, 4GB RAM, 40GB...`,
    overview: `Überblick
Hetzner CX21 als Basis für alle Schimmilab-Services. Günstig, zuverlässig, in Deutschland gehostet.
Stack
Server: Hetzner CX21 (2 vCPU, 4GB RAM, 40GB SSD NVMe)
OS: Ubuntu 24.04 LTS
Backup: Hetzner Storage Box 100GB (~3€/Monat)
Firewall: UFW (nur Port 80, 443, 51820 offen)
Setup
# Initial …`,
    stack: ``,
    architecture: ``,
    setup: ``,
    costs: ``,
    security: ``,
    code: ``,
    learnings: ``,
  },
  {
    id: "test",
    anytype_id: "bafyreiacr6zijfckvigwmxnkn3iemscgp7jkndwlycgjhwimnh5nnb5gem",
    title: `Test`,
    category: `Infrastruktur`,
    tags: ["Infrastruktur"],
    date: "2026-03-21",
    status: "active",
    statusColor: "text-emerald-400",
    statusLabel: "Aktiv",
    excerpt: `Infrastruktur-Dokumentation: Test`,
    overview: `Infrastruktur-Dokumentation: Test`,
    stack: ``,
    architecture: ``,
    setup: ``,
    costs: ``,
    security: ``,
    code: ``,
    learnings: ``,
  },
];

export const getInfraItemById = (id: string): InfraItem | undefined =>
  infraItems.find((i) => i.id === id);

export const getInfraItemsByCategory = (category: string): InfraItem[] =>
  infraItems.filter((i) => i.category === category);
