// AUTO-GENERATED by scripts/sync-anytype.py
// Last sync: 2026-06-08T20:21:56.479616
// DO NOT EDIT MANUALLY – edit in Anytype Schimmilab Space instead

export interface Thought {
  id: string;
  title: string;
  tags: string[];
  date: string;
  readTime: number;
  excerpt: string;
  content: string;
}

export const thoughts: Thought[] = [
  {
    id: "warum-ich-alles-selbst-hoste",
    title: `Warum ich alles selbst hoste`,
    tags: ["Gedanke"],
    date: "2026-03-21",
    readTime: 1,
    excerpt: `Nicht aus Paranoia. Sondern weil ich verstehen will wie es funktioniert. Ich könnte Vercel nutzen für die Website. Ich könnte Notion für Notizen. Ich könnte...`,
    content: `Nicht aus Paranoia. Sondern weil ich verstehen will wie es funktioniert.   
Ich könnte Vercel nutzen für die Website. Ich könnte Notion für Notizen. Ich könnte GitHub Pages, Netlify, Cloudflare Pages. Alles wäre einfacher.   
Aber dann würde ich nicht verstehen wie ein Reverse Proxy funktioniert. Ich würde nicht wissen wie Docker Networking intern arbeitet. Ich würde nie die Freude erleben, wenn ein selbst konfiguriertes TLS-Zertifikat zum ersten Mal grün wird.   
Self-Hosting ist für mich kein politisches Statement. Es ist ein Lernprojekt.   
Jedes Problem das auftaucht – ein Service der nicht startet, ein Zertifikat das abläuft, ein Backup das fehlschlägt – ist eine Lernmöglichkeit. Und weil es meine eigene Infrastruktur ist, habe ich die Freiheit, Fehler zu machen und daraus zu lernen ohne Konsequenzen für andere.   
Das ist der Kern von Schimmilab: Dokumentierte Neugier. Nicht perfekte Lösungen, sondern ehrliche Experimente.   
`,
  },
  {
    id: "kontrolle-vs-autonomie-in-verteilten-systemen",
    title: `Kontrolle vs. Autonomie in verteilten Systemen`,
    tags: ["Gedanke"],
    date: "2026-03-21",
    readTime: 1,
    excerpt: `Was Kubernetes und Selbstorganisation gemeinsam haben – und warum beides scheitert, wenn man es falsch versteht. Kubernetes ist im Kern ein System, das...`,
    content: `Was Kubernetes und Selbstorganisation gemeinsam haben – und warum beides scheitert, wenn man es falsch versteht.   
Kubernetes ist im Kern ein System, das Kontrolle durch Autonomie ersetzt. Du sagst nicht "starte Container X auf Node Y", du sagst "ich will 3 Replicas von Service Z" und der Scheduler entscheidet selbst wie das umgesetzt wird.   
Das ist mächtig. Und das ist auch genau der Punkt wo viele Teams scheitern.   
Das Problem: Wir sind als Ingenieure trainiert, Kontrolle zu wollen. Wir wollen wissen was wo läuft. Wir wollen vorhersagen können was passiert. Kubernetes nimmt uns diese Kontrolle weg – und gibt uns dafür Resilienz und Skalierbarkeit.   
Der Fehler den ich immer wieder sehe: Teams versuchen Kubernetes zu "kontrollieren". Sie schreiben NodeSelectors für jeden Pod, sie pinnen Versionen auf spezifische Nodes, sie kämpfen gegen den Scheduler. Das Ergebnis ist ein System das die Komplexität von Kubernetes hat, aber keine der Vorteile.   
Dasselbe gilt für Self-Hosting: Wenn du jeden Aspekt deiner Infrastruktur manuell kontrollieren willst, wirst du scheitern. Nicht weil du nicht gut genug bist, sondern weil Komplexität exponentiell wächst.   
Die Lösung ist Vertrauen. Vertrauen in das System, in die Abstraktion, in die Automatisierung. Und das ist für uns Ingenieure oft das Schwerste.   
`,
  },
  {
    id: "ki-als-werkzeug-oder-als-gegenueber",
    title: `KI als Werkzeug oder als Gegenüber?`,
    tags: ["Gedanke"],
    date: "2026-03-21",
    readTime: 1,
    excerpt: `Die Frage ist nicht ob KI denkt, sondern was wir tun, wenn wir so tun als ob. Ich benutze KI täglich als Werkzeug – für Code, für Texte, für Recherche. Und...`,
    content: `Die Frage ist nicht ob KI denkt, sondern was wir tun, wenn wir so tun als ob.   
Ich benutze KI täglich als Werkzeug – für Code, für Texte, für Recherche. Und trotzdem ertappe ich mich dabei, wie ich manchmal mit Claude oder GPT spreche als wäre da jemand. Nicht weil ich glaube, dass da Bewusstsein ist. Sondern weil das Interface so gestaltet ist, dass es sich so anfühlt.   
Das ist kein Bug, das ist ein Feature. Und gleichzeitig eine Falle.   
Wenn wir KI-Systeme so bauen, dass sie menschlich wirken, dann verändern wir damit auch wie wir über Intelligenz, Empathie und Verantwortung nachdenken. Wir projizieren Eigenschaften auf Systeme, die diese Eigenschaften nicht haben – und handeln dann entsprechend.   
Die interessante Frage ist nicht "Ist KI intelligent?" sondern "Was passiert mit uns, wenn wir so tun als ob?"   
Als DevOps-Engineer sehe ich das täglich: KI-Assistenten in IDEs verändern wie Entwickler über Code nachdenken. Nicht weil die KI besser ist, sondern weil die Interaktion anders ist. Schneller. Dialogischer. Weniger Dokumentation lesen, mehr fragen.   
Ist das gut? Ist das schlecht? Ich weiß es ehrlich gesagt nicht. Aber ich finde es wichtig, es zu beobachten.   
`,
  },
];

export const getThoughtById = (id: string): Thought | undefined =>
  thoughts.find((t) => t.id === id);
