// AUTO-GENERATED by scripts/sync-anytype.py
// Last sync: 2026-03-21T15:19:12.539665
// DO NOT EDIT MANUALLY – edit in Anytype Schimmilab Space instead

export interface Thought {
  id: string;
  title: string;
  tags: string[];
  date: string;
  readTime: number;
  excerpt: string;
  content: string;
}

export const thoughts: Thought[] = [
];

export const getThoughtById = (id: string): Thought | undefined =>
  thoughts.find((t) => t.id === id);
