// AUTO-GENERATED by scripts/sync-anytype.py
// Last sync: 2026-03-21T16:24:12.179820
// DO NOT EDIT MANUALLY – edit in Anytype Schimmilab Space instead

export interface Thought {
  id: string;
  title: string;
  tags: string[];
  date: string;
  readTime: number;
  excerpt: string;
  content: string;
}

export const thoughts: Thought[] = [
  {
    id: "warum-ich-alles-selbst-hoste",
    title: `Warum ich alles selbst hoste`,
    tags: ["Gedanke"],
    date: "2026-03-21",
    readTime: 1,
    excerpt: `Nicht aus Paranoia. Sondern weil ich verstehen will wie es funktioniert. Ich könnte Vercel nutzen für die Website. Ich könnte Notion für Notizen. Ich könnte...`,
    content: `Nicht aus Paranoia. Sondern weil ich verstehen will wie es funktioniert.
Ich könnte Vercel nutzen für die Website. Ich könnte Notion für Notizen. Ich könnte GitHub Pages, Netlify, Cloudflare Pages. Alles wäre einfacher.
Aber dann würde ich nicht verstehen wie ein Reverse Proxy funktioniert. Ich …`,
  },
  {
    id: "kontrolle-vs-autonomie-in-verteilten-systemen",
    title: `Kontrolle vs. Autonomie in verteilten Systemen`,
    tags: ["Gedanke"],
    date: "2026-03-21",
    readTime: 1,
    excerpt: `Was Kubernetes und Selbstorganisation gemeinsam haben – und warum beides scheitert, wenn man es falsch versteht. Kubernetes ist im Kern ein System, das...`,
    content: `Was Kubernetes und Selbstorganisation gemeinsam haben – und warum beides scheitert, wenn man es falsch versteht.
Kubernetes ist im Kern ein System, das Kontrolle durch Autonomie ersetzt. Du sagst nicht "starte Container X auf Node Y", du sagst "ich will 3 Replicas von Service Z" und der Scheduler …`,
  },
  {
    id: "ki-als-werkzeug-oder-als-gegenueber",
    title: `KI als Werkzeug oder als Gegenüber?`,
    tags: ["Gedanke"],
    date: "2026-03-21",
    readTime: 1,
    excerpt: `Die Frage ist nicht ob KI denkt, sondern was wir tun, wenn wir so tun als ob. Ich benutze KI täglich als Werkzeug – für Code, für Texte, für Recherche. Und...`,
    content: `Die Frage ist nicht ob KI denkt, sondern was wir tun, wenn wir so tun als ob.
Ich benutze KI täglich als Werkzeug – für Code, für Texte, für Recherche. Und trotzdem ertappe ich mich dabei, wie ich manchmal mit Claude oder GPT spreche als wäre da jemand. Nicht weil ich glaube, dass da Bewusstsein …`,
  },
];

export const getThoughtById = (id: string): Thought | undefined =>
  thoughts.find((t) => t.id === id);
